server:
  port: 18061

spring:
  application:
    name: spring-boot-admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:18001/eureka/,http://peer2:18002/eureka/

management:
  security:
    enabled: false
